[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "frontend/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "20"
  # Les variables d'environnement doivent être configurées dans le dashboard Netlify
  # Ne pas définir les variables ici car elles ne sont pas correctement substituées

[dev]
  framework = "vite"
  targetPort = 5173
