[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://your-project.supabase.co"

[dev]
  framework = "vite"
  targetPort = 5173
